# Generated by Django 5.2.6 on 2025-09-18 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('UserType', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medicine', models.CharField(blank=True, max_length=30, null=True)),
                ('Description', models.CharField(blank=True, max_length=30, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('PhNumber', models.BigIntegerField(blank=True, null=True)),
                ('Specialization', models.CharField(blank=True, max_length=30, null=True)),
                ('HospitalName', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainTumorDetectionApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=30, null=True)),
                ('PhNumber', models.BigIntegerField(blank=True, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainTumorDetectionApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='AppoinmentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainTumorDetectionApp.doctortable')),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainTumorDetectionApp.patienttable')),
            ],
        ),
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(blank=True, null=True, upload_to='')),
                ('Document', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainTumorDetectionApp.doctortable')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription', models.CharField(blank=True, max_length=300, null=True)),
                ('DOCTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainTumorDetectionApp.doctortable')),
                ('Medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainTumorDetectionApp.medicinetable')),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BrainTumorDetectionApp.patienttable')),
            ],
        ),
    ]
