# Generated by Django 5.2.6 on 2025-12-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTumorDetectionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortable',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
