# Generated by Django 5.2.6 on 2025-12-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTumorDetectionApp', '0002_doctortable_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinmenttable',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
