# Generated by Django 5.2.6 on 2025-12-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTumorDetectionApp', '0003_appoinmenttable_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notification', models.CharField(blank=True, max_length=300, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='posttable',
            name='Document',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
