# Generated by Django 5.2.6 on 2025-12-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTumorDetectionApp', '0004_notificationtable_alter_posttable_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinmenttable',
            name='create_date',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notificationtable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttable',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
