# Generated by Django 5.2.6 on 2025-12-15 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTumorDetectionApp', '0005_appoinmenttable_create_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptiontable',
            name='Medicine',
        ),
    ]
