# Generated by Django 5.2.6 on 2025-12-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BrainTumorDetectionApp', '0006_remove_prescriptiontable_medicine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
